name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }} 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag finanza-che-conta:$(date +%s)
    - name: Push Docker image
      run: |
        docker tag finanza-che-conta:latest ${{ env.DOCKER_USERNAME }}/finanza-che-conta:latest
        docker push ${{ env.DOCKER_USERNAME }}/finanza-che-conta:latest
    

